# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "availabilities", :force => true do |t|
    t.column "double_room",     :string
    t.column "single_room",     :string
    t.column "triple_room",     :string
    t.column "twin_room",       :string
    t.column "booking_info_id", :integer
  end

  create_table "booking_infos", :force => true do |t|
    t.column "date",            :date
    t.column "weekend",         :boolean
    t.column "rate_special_id", :integer
  end

  create_table "bookings", :force => true do |t|
    t.column "arrival_date",     :date
    t.column "departure_date",   :date
    t.column "availability_id",  :integer
    t.column "rate_id",          :integer
    t.column "amount",           :integer
    t.column "number_of_nights", :integer
    t.column "room_id",          :integer
  end

  create_table "rate_specials", :force => true do |t|
    t.column "shortname", :string
    t.column "longname",  :string
  end

  create_table "rates", :force => true do |t|
    t.column "date",            :date
    t.column "double_room",     :string
    t.column "single_room",     :string
    t.column "triple_room",     :string
    t.column "twin_room",       :string
    t.column "weekend",         :boolean
    t.column "rate_special_id", :integer
  end

  create_table "rooms", :force => true do |t|
    t.column "room",        :string
    t.column "description", :string
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

end
